# Technical Architecture Package
# Version 1.0.0 - Initial release

doc_type_id: technical_architecture
display_name: "Technical Architecture"
version: "1.0.0"
description: >
  Comprehensive technical architecture including components, interfaces,
  data models, workflows, and quality attributes. Built after primary
  implementation plan, informs final planning.

# Classification
authority_level: prescriptive  # Prescriptive - defines how things should be built
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering
view_docdef: ArchitecturalSummaryView

# Dependencies
required_inputs:
  - project_discovery
  - primary_implementation_plan
  - implementation_plan
optional_inputs: []
creates_children: []
parent_doc_type: null

# Shared artifact references
role_prompt_ref: "prompt:role:technical_architect:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
schema_ref: "schema:technical_architecture:1.0.0"

# Packaged artifacts
artifacts:
  task_prompt: "prompts/task.prompt.txt"
  qa_prompt: null
  pgc_context: null  # PGC is a standalone fragment: prompt:pgc:technical_architecture:1.0.0
  questions_prompt: null
  schema: "schemas/output.schema.json"

# Tests
tests:
  fixtures: []
  golden_traces: []

# Gating rules
gating_rules:
  lifecycle_states: []
  design_status: []
  acceptance_required: false
  accepted_by: []

# Information Architecture (ADR-054)
information_architecture:
  version: 2

  sections:
    - id: overview.summary
      label: Architecture Summary
      binds:
        - path: architecture_summary
          render_as: nested-object
          fields:
            - path: title
              render_as: paragraph
            - path: style
              render_as: paragraph
            - path: key_decisions
              render_as: list

    - id: overview.risks
      label: Risks
      binds:
        - path: risks
          render_as: table
          columns:
            - field: risk
              label: Risk
            - field: impact
              label: Impact
            - field: mitigation
              label: Mitigation
            - field: status
              label: Status

    - id: overview.open_questions
      label: Open Questions
      binds:
        - path: open_questions
          render_as: table
          columns:
            - field: question
              label: Question
            - field: impact
              label: Impact
            - field: default_assumption
              label: Default Assumption

    - id: overview.mvp_scope
      label: MVP Scope
      binds:
        - path: mvp_scope
          render_as: nested-object
          fields:
            - path: included
              render_as: list
            - path: deferred
              render_as: list

    - id: components
      label: Components
      binds:
        - path: components
          render_as: card-list
          card:
            title: name
            fields:
              - path: purpose
                render_as: paragraph
              - path: technology
                render_as: paragraph
              - path: interfaces
                render_as: list
              - path: dependencies
                render_as: list

    - id: workflows
      label: Workflows
      binds:
        - path: workflows
          render_as: card-list
          card:
            title: name
            fields:
              - path: trigger
                render_as: paragraph
              - path: steps
                render_as: table
                columns:
                  - field: step
                    label: "#"
                  - field: action
                    label: Action
                  - field: component
                    label: Component
                  - field: output
                    label: Output

    - id: data_models
      label: Data Models
      binds:
        - path: data_models
          render_as: card-list
          card:
            title: entity_name
            fields:
              - path: description
                render_as: paragraph
              - path: fields
                render_as: table
                columns:
                  - field: name
                    label: Field
                  - field: type
                    label: Type
                  - field: required
                    label: Required
                  - field: description
                    label: Description
              - path: relationships
                render_as: list

    - id: api_interfaces
      label: API Interfaces
      binds:
        - path: api_interfaces
          render_as: card-list
          card:
            title: name
            fields:
              - path: type
                render_as: paragraph
              - path: endpoints
                render_as: table
                columns:
                  - field: method
                    label: Method
                  - field: path
                    label: Path
                  - field: description
                    label: Description

    - id: quality_attributes
      label: Quality Attributes
      binds:
        - path: quality_attributes
          render_as: nested-object
          fields:
            - path: performance
              render_as: list
            - path: security
              render_as: list
            - path: scalability
              render_as: list
            - path: maintainability
              render_as: list
            - path: observability
              render_as: list

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview.summary
          - overview.risks
          - overview.open_questions
          - overview.mvp_scope

      - id: components
        label: Components
        sections:
          - components

      - id: workflows
        label: Workflows
        sections:
          - workflows

      - id: data_models
        label: Data Models
        sections:
          - data_models

      - id: interfaces
        label: APIs
        sections:
          - api_interfaces

      - id: quality
        label: Quality
        sections:
          - quality_attributes

  pdf:
    linear_order:
      - overview.summary
      - overview.risks
      - overview.open_questions
      - overview.mvp_scope
      - components
      - workflows
      - data_models
      - api_interfaces
      - quality_attributes
    toc: true

# UI configuration
ui:
  icon: landmark
  category: architecture
  display_order: 30
