# Technical Architecture Package
# Version 1.0.0 - Initial release

doc_type_id: technical_architecture
display_name: "Technical Architecture"
version: "1.0.0"
description: >
  Comprehensive technical architecture including components, interfaces,
  data models, workflows, and quality attributes. Built after primary
  implementation plan, informs final planning.

# Classification
authority_level: prescriptive  # Prescriptive - defines how things should be built
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering
view_docdef: ArchitecturalSummaryView

# Dependencies
required_inputs:
  - project_discovery
  - primary_implementation_plan
  - implementation_plan
optional_inputs: []
creates_children: []
parent_doc_type: null

# Shared artifact references
role_prompt_ref: "prompt:role:technical_architect:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
schema_ref: "schema:technical_architecture:1.0.0"

# Packaged artifacts
artifacts:
  task_prompt: "prompts/task.prompt.txt"
  qa_prompt: null
  pgc_context: null  # PGC is a standalone fragment: prompt:pgc:technical_architecture:1.0.0
  questions_prompt: null
  schema: "schemas/output.schema.json"

# Tests
tests:
  fixtures: []
  golden_traces: []

# Gating rules
gating_rules:
  lifecycle_states: []
  design_status: []
  acceptance_required: false
  accepted_by: []

# Information Architecture (ADR-054)
information_architecture:
  version: 1

  sections:
    - id: overview.summary
      label: Architecture Summary
      binds:
        - architecture_summary

    - id: overview.risks
      label: Risks
      binds:
        - risks

    - id: overview.open_questions
      label: Open Questions
      binds:
        - open_questions

    - id: overview.mvp_scope
      label: MVP Scope
      binds:
        - mvp_scope

    - id: components
      label: Components
      binds:
        - components

    - id: workflows
      label: Workflows
      binds:
        - workflows

    - id: data_models
      label: Data Models
      binds:
        - data_models

    - id: api_interfaces
      label: API Interfaces
      binds:
        - api_interfaces

    - id: quality_attributes
      label: Quality Attributes
      binds:
        - quality_attributes

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview.summary
          - overview.risks
          - overview.open_questions
          - overview.mvp_scope

      - id: components
        label: Components
        sections:
          - components

      - id: workflows
        label: Workflows
        sections:
          - workflows

      - id: data_models
        label: Data Models
        sections:
          - data_models

      - id: interfaces
        label: APIs
        sections:
          - api_interfaces

      - id: quality
        label: Quality
        sections:
          - quality_attributes

  pdf:
    linear_order:
      - overview.summary
      - overview.risks
      - overview.open_questions
      - overview.mvp_scope
      - components
      - workflows
      - data_models
      - api_interfaces
      - quality_attributes
    toc: true

# UI configuration
ui:
  icon: landmark
  category: architecture
  display_order: 30
