# Technical Architecture Package
# Version 1.0.0 - Initial release

doc_type_id: technical_architecture
display_name: "Technical Architecture"
version: "1.0.0"
description: >
  Comprehensive technical architecture including components, interfaces,
  data models, workflows, and quality attributes. Built after primary
  implementation plan, informs final planning.

# Classification
authority_level: prescriptive  # Prescriptive - defines how things should be built
creation_mode: llm_generated
production_mode: generate
scope: project

# Dependencies
required_inputs:
  - project_discovery
  - primary_implementation_plan
optional_inputs: []
creates_children: []
parent_doc_type: null

# Shared artifact references
role_prompt_ref: "prompt:role:technical_architect:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
schema_ref: "schema:technical_architecture:1.0.0"

# Packaged artifacts
artifacts:
  task_prompt: "prompts/task.prompt.txt"
  qa_prompt: null
  pgc_context: null
  questions_prompt: null
  schema: "schemas/output.schema.json"

# Tests
tests:
  fixtures: []
  golden_traces: []

# Gating rules
gating_rules:
  lifecycle_states: []
  design_status: []
  acceptance_required: false
  accepted_by: []

# UI configuration
ui:
  icon: landmark
  category: architecture
  display_order: 30
