# Document Type Package Manifest
# Schema: ../../../schemas/registry/package.schema.json

doc_type_id: project_discovery
display_name: Project Discovery
version: 1.4.0

description: >
  Early architectural discovery performed before PM decomposition.
  Surfaces critical questions, identifies constraints and risks,
  proposes candidate directions, and establishes guardrails.

# Classification (per ADR-044)
authority_level: descriptive
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering
view_docdef: ProjectDiscovery

# Dependencies
required_inputs: []  # First document in workflow - no dependencies
optional_inputs: []

# Shared artifact references
role_prompt_ref: "prompt:role:technical_architect:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
qa_template_ref: "prompt:template:qa_evaluator:1.0.0"
pgc_template_ref: "prompt:template:pgc_clarifier:1.0.0"
schema_ref: "schema:project_discovery:1.4.0"

# Packaged artifacts (relative paths)
artifacts:
  task_prompt: prompts/task.prompt.txt
  qa_prompt: prompts/qa.prompt.txt
  pgc_context: prompts/pgc_context.prompt.txt
  # questions_prompt: prompts/questions.prompt.txt  # TODO: migrate if exists
  schema: schemas/output.schema.json
  # full_docdef: docdefs/full.docdef.json  # TODO: create
  # sidecar_docdef: docdefs/sidecar.docdef.json  # TODO: create
  # gating_rules: rules/gating.rules.json  # Not applicable for descriptive docs

# Test artifacts
tests:
  fixtures: []
  golden_traces: []

# Information Architecture (ADR-054)
information_architecture:
  version: 2

  sections:
    - id: overview.summary
      label: Preliminary Summary
      binds:
        - path: preliminary_summary
          render_as: nested-object
          fields:
            - path: problem_understanding
              render_as: paragraph
            - path: architectural_intent
              render_as: paragraph
            - path: proposed_system_shape
              render_as: paragraph

    - id: overview.project_name
      label: Project Name
      binds:
        - path: project_name
          render_as: paragraph

    - id: discovery.unknowns
      label: Unknowns
      binds:
        - path: unknowns
          render_as: table
          columns:
            - field: id
              label: ID
            - field: question
              label: Question
            - field: why_it_matters
              label: Why It Matters
            - field: impact_if_unresolved
              label: Impact If Unresolved

    - id: discovery.assumptions
      label: Assumptions
      binds:
        - path: assumptions
          render_as: table
          columns:
            - field: id
              label: ID
            - field: assumption
              label: Assumption
            - field: confidence
              label: Confidence
            - field: validation_approach
              label: Validation

    - id: discovery.constraints
      label: Known Constraints
      binds:
        - path: known_constraints
          render_as: table
          columns:
            - field: id
              label: ID
            - field: constraint
              label: Constraint
            - field: constraint_type
              label: Type

    - id: risks
      label: Risks
      binds:
        - path: risks
          render_as: table
          columns:
            - field: id
              label: ID
            - field: description
              label: Risk
            - field: likelihood
              label: Likelihood
            - field: impact
              label: Impact
            - field: impact_on_planning
              label: Planning Impact
            - field: mitigation_direction
              label: Mitigation

    - id: risks.guardrails
      label: MVP Guardrails
      binds:
        - path: mvp_guardrails
          render_as: table
          columns:
            - field: id
              label: ID
            - field: guardrail
              label: Guardrail

    - id: decisions
      label: Early Decision Points
      binds:
        - path: early_decision_points
          render_as: card-list
          card:
            title: decision_area
            fields:
              - path: id
                render_as: paragraph
              - path: why_early
                render_as: paragraph
              - path: options
                render_as: list
              - path: recommendation_direction
                render_as: paragraph

    - id: stakeholders.questions
      label: Stakeholder Questions
      binds:
        - path: stakeholder_questions
          render_as: table
          columns:
            - field: id
              label: ID
            - field: question
              label: Question
            - field: directed_to
              label: Directed To
            - field: blocking
              label: Blocking

    - id: stakeholders.recommendations
      label: Recommendations for PM
      binds:
        - path: recommendations_for_pm
          render_as: table
          columns:
            - field: id
              label: ID
            - field: recommendation
              label: Recommendation

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview.summary
          - overview.project_name

      - id: discovery
        label: Discovery
        sections:
          - discovery.unknowns
          - discovery.assumptions
          - discovery.constraints

      - id: risks_tab
        label: Risks
        sections:
          - risks
          - risks.guardrails

      - id: decisions_tab
        label: Decisions
        sections:
          - decisions
          - stakeholders.questions
          - stakeholders.recommendations

  pdf:
    linear_order:
      - overview.project_name
      - overview.summary
      - discovery.unknowns
      - discovery.assumptions
      - discovery.constraints
      - risks
      - risks.guardrails
      - decisions
      - stakeholders.questions
      - stakeholders.recommendations
    toc: true

# UI configuration
ui:
  icon: search
  category: architecture
  display_order: 10
