"""Add intent_packet and backlog_item document types

Revision ID: 20260216_003
Revises: 20260216_002
Create Date: 2026-02-16

Per WS-BCP-001 Phase 1.

Registers intent_packet (single, manual intake) and backlog_item (multi-instance,
LLM-generated) document types for the Backlog Compilation Pipeline.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20260216_003"
down_revision = "20260216_002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # intent_packet: mechanical intake, no LLM, single-instance
    op.execute("""
        INSERT INTO document_types (
            id, doc_type_id, name, description, category, icon,
            schema_version, builder_role, builder_task, handler_id,
            required_inputs, optional_inputs, gating_rules,
            acceptance_required, cardinality, instance_key,
            scope, display_order, is_active, version
        ) VALUES (
            gen_random_uuid(),
            'intent_packet',
            'Intent Packet',
            'Raw user intent persisted as immutable input to the Backlog Compilation Pipeline.',
            'planning',
            'lightbulb',
            '1.0.0',
            'project_manager',
            'intake',
            'intent_packet',
            '[]'::jsonb,
            '[]'::jsonb,
            '{}'::jsonb,
            false,
            'single',
            NULL,
            'project',
            1,
            true,
            '1.0.0'
        )
    """)

    # backlog_item: LLM-generated, multi-instance keyed by item id
    op.execute("""
        INSERT INTO document_types (
            id, doc_type_id, name, description, category, icon,
            schema_version, builder_role, builder_task, handler_id,
            required_inputs, optional_inputs, gating_rules,
            acceptance_required, cardinality, instance_key,
            scope, display_order, is_active, version
        ) VALUES (
            gen_random_uuid(),
            'backlog_item',
            'Backlog Item',
            'Unified backlog item (EPIC/FEATURE/STORY) generated by the Backlog Generator DCW.',
            'planning',
            'list',
            '1.0.0',
            'project_manager',
            'backlog_generator',
            'backlog_item',
            '["intent_packet"]'::jsonb,
            '[]'::jsonb,
            '{}'::jsonb,
            false,
            'multi',
            'id',
            'project',
            2,
            true,
            '1.0.0'
        )
    """)


def downgrade() -> None:
    op.execute("DELETE FROM document_types WHERE doc_type_id = 'backlog_item'")
    op.execute("DELETE FROM document_types WHERE doc_type_id = 'intent_packet'")
