# Document Type Package Manifest
# Schema: ../../../schemas/registry/package.schema.json

doc_type_id: primary_implementation_plan
display_name: Preliminary Implementation Plan
version: 1.0.0
status: deprecated

description: >
  DEPRECATED: Collapsed into implementation_plan by WS-PIPELINE-001.
  Previously the preliminary implementation plan produced before technical
  architecture. Contained Work Package candidates that informed architectural
  decisions. All functionality now in the unified implementation_plan type.

# Classification (per ADR-044)
authority_level: prescriptive
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering — IA-driven (ADR-054), no DocDef needed
# view_docdef: ImplementationPlanPrimaryView  # TODO: create if legacy path needed

# Dependencies
required_inputs:
  - project_discovery
optional_inputs: []

# Shared artifact references
role_prompt_ref: "prompt:role:project_manager:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
qa_template_ref: "prompt:template:qa_evaluator:1.0.0"
pgc_template_ref: "prompt:template:pgc_clarifier:1.0.0"
schema_ref: "schema:primary_implementation_plan:1.0.0"

# Packaged artifacts (relative paths)
artifacts:
  task_prompt: prompts/task.prompt.txt
  # qa_prompt: prompts/qa.prompt.txt  # TODO: create
  pgc_context: prompts/pgc_context.prompt.txt
  schema: schemas/output.schema.json
  # full_docdef: docdefs/full.docdef.json  # TODO: create
  # sidecar_docdef: docdefs/sidecar.docdef.json  # TODO: create

# Test artifacts
tests:
  fixtures: []
  golden_traces: []

# Information Architecture (ADR-054)
information_architecture:
  version: 2

  sections:
    - id: overview
      label: Plan Summary
      binds:
        - path: epic_set_summary
          render_as: nested-object
          fields:
            - path: overall_intent
              render_as: paragraph
            - path: mvp_definition
              render_as: paragraph
            - path: key_constraints
              render_as: list
            - path: out_of_scope
              render_as: list

    - id: candidates
      label: Work Package Candidates
      binds:
        - path: work_package_candidates
          render_as: card-list
          card:
            title: title
            fields:
              - path: candidate_id
                render_as: paragraph
              - path: rationale
                render_as: paragraph
              - path: scope_in
                render_as: list
              - path: scope_out
                render_as: list
              - path: dependencies
                render_as: list
              - path: definition_of_done
                render_as: list
              - path: governance_notes
                render_as: list
              - path: associated_risks
                render_as: list

    - id: risks
      label: Risks Overview
      binds:
        - path: risks_overview
          render_as: table
          columns:
            - field: risk_id
              label: ID
            - field: description
              label: Risk
            - field: affected_candidates
              label: Affected Candidates
            - field: mitigation_direction
              label: Mitigation

    - id: recommendations
      label: Architecture Recommendations
      binds:
        - path: recommendations_for_architecture
          render_as: list

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview

      - id: candidates
        label: WP Candidates
        sections:
          - candidates

      - id: risks
        label: Risks
        sections:
          - risks

      - id: recommendations
        label: Recommendations
        sections:
          - recommendations

  pdf:
    linear_order:
      - overview
      - candidates
      - risks
      - recommendations
    toc: true

# UI configuration
ui:
  icon: map
  category: planning
  display_order: 25
