# Document Type Package Manifest
# Schema: ../../../schemas/registry/package.schema.json

doc_type_id: primary_implementation_plan
display_name: Implementation Plan (Primary)
version: 1.0.0

description: >
  Preliminary implementation plan produced before technical architecture.
  Contains Work Package candidates that inform architectural decisions.
  WP candidates are not yet commitments - they become Work Packages
  after architecture review via IPF reconciliation.

# Classification (per ADR-044)
authority_level: prescriptive
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering
view_docdef: ImplementationPlanPrimaryView

# Dependencies
required_inputs:
  - project_discovery
optional_inputs: []

# Shared artifact references
role_prompt_ref: "prompt:role:project_manager:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
qa_template_ref: "prompt:template:qa_evaluator:1.0.0"
pgc_template_ref: "prompt:template:pgc_clarifier:1.0.0"
schema_ref: "schema:primary_implementation_plan:1.0.0"

# Packaged artifacts (relative paths)
artifacts:
  task_prompt: prompts/task.prompt.txt
  # qa_prompt: prompts/qa.prompt.txt  # TODO: create
  pgc_context: prompts/pgc_context.prompt.txt
  schema: schemas/output.schema.json
  # full_docdef: docdefs/full.docdef.json  # TODO: create
  # sidecar_docdef: docdefs/sidecar.docdef.json  # TODO: create

# Test artifacts
tests:
  fixtures: []
  golden_traces: []

# Information Architecture (ADR-054)
information_architecture:
  version: 1

  sections:
    - id: overview
      label: Plan Summary
      binds:
        - epic_set_summary

    - id: candidates
      label: Work Package Candidates
      binds:
        - work_package_candidates

    - id: risks
      label: Risks Overview
      binds:
        - risks_overview

    - id: recommendations
      label: Architecture Recommendations
      binds:
        - recommendations_for_architecture

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview

      - id: candidates
        label: WP Candidates
        sections:
          - candidates

      - id: risks
        label: Risks
        sections:
          - risks

      - id: recommendations
        label: Recommendations
        sections:
          - recommendations

  pdf:
    linear_order:
      - overview
      - candidates
      - risks
      - recommendations
    toc: true

# UI configuration
ui:
  icon: map
  category: planning
  display_order: 25
