# Implementation Plan Package
# Version 1.0.0 - Consolidated (WP-PIPELINE-001)

doc_type_id: implementation_plan
display_name: "Implementation Plan"
version: "1.0.0"
description: >
  Unified implementation plan produced from project discovery. Contains
  candidate Work Packages (advisory), risk analysis, and architecture
  recommendations. Candidates are promoted to governed WPs after TA review.

# Classification
authority_level: prescriptive  # Prescriptive - defines what will be built
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering
view_docdef: ImplementationPlanView

# Dependencies
required_inputs:
  - project_discovery
optional_inputs: []
creates_children: []
parent_doc_type: null

# Shared artifact references
role_prompt_ref: "prompt:role:project_manager:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
schema_ref: "schema:implementation_plan:1.0.0"

# Packaged artifacts
artifacts:
  task_prompt: "prompts/task.prompt.txt"
  qa_prompt: null
  pgc_context: "prompts/pgc_context.prompt.txt"
  questions_prompt: null
  schema: "schemas/output.schema.json"

# Tests
tests:
  fixtures: []
  golden_traces: []

# Gating rules
gating_rules:
  lifecycle_states: []
  design_status: []
  acceptance_required: true  # Requires acceptance before spawning WPs
  accepted_by:
    - stakeholder
    - technical_lead

# Information Architecture (ADR-054)
information_architecture:
  version: 2

  sections:
    - id: overview
      label: Plan Summary
      binds:
        - path: plan_summary
          render_as: nested-object
          fields:
            - path: overall_intent
              render_as: paragraph
            - path: mvp_definition
              render_as: paragraph
            - path: key_constraints
              render_as: list
            - path: sequencing_rationale
              render_as: paragraph
            - path: assumptions
              render_as: list
            - path: out_of_scope
              render_as: list

    - id: work_packages
      label: Work Package Candidates
      binds:
        - path: work_package_candidates
          render_as: card-list
          card:
            title: title
            fields:
              - path: candidate_id
                render_as: paragraph
              - path: rationale
                render_as: paragraph
              - path: scope_in
                render_as: list
              - path: scope_out
                render_as: list
              - path: dependencies
                render_as: table
                columns:
                  - field: depends_on_candidate_id
                    label: Depends On
                  - field: depends_on_external
                    label: External Dep
                  - field: dependency_type
                    label: Type
                  - field: notes
                    label: Notes
              - path: definition_of_done
                render_as: list
              - path: notes_for_work_binder
                render_as: paragraph

    - id: risks
      label: Risk Summary
      binds:
        - path: risk_summary
          render_as: table
          columns:
            - field: risk
              label: Risk
            - field: affected_candidates
              label: Affected Candidates
            - field: overall_impact
              label: Impact
            - field: mitigation_strategy
              label: Mitigation

    - id: concerns
      label: Cross-Cutting Concerns
      binds:
        - path: cross_cutting_concerns
          render_as: list

    - id: architecture_recs
      label: Architecture Recommendations
      binds:
        - path: recommendations_for_architecture
          render_as: list

    - id: open_questions
      label: Open Questions
      binds:
        - path: open_questions
          render_as: table
          columns:
            - field: question
              label: Question
            - field: why_it_matters
              label: Why It Matters
            - field: who_needs_to_answer
              label: Owner
            - field: status
              label: Status

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview

      - id: work_packages
        label: Candidates
        sections:
          - work_packages

      - id: risks_concerns
        label: Risks & Concerns
        sections:
          - risks
          - concerns

      - id: architecture
        label: Architecture
        sections:
          - architecture_recs
          - open_questions

  pdf:
    linear_order:
      - overview
      - work_packages
      - risks
      - concerns
      - architecture_recs
      - open_questions
    toc: true

# UI configuration
ui:
  icon: git-branch
  category: planning
  display_order: 35
