# Implementation Plan (Final) Package
# Version 1.0.0 - Initial release

doc_type_id: implementation_plan
display_name: "Implementation Plan"
version: "1.0.0"
description: >
  Final implementation plan produced after technical architecture review.
  Reconciles WP candidates into committed Work Packages with governance
  pinning. Creating this document spawns individual Work Package documents.

# Classification
authority_level: prescriptive  # Prescriptive - defines what will be built
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering
view_docdef: ImplementationPlanView

# Dependencies
required_inputs:
  - primary_implementation_plan
  - project_discovery
optional_inputs: []
creates_children:
  - work_package
parent_doc_type: null

# Shared artifact references
role_prompt_ref: "prompt:role:project_manager:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
schema_ref: "schema:implementation_plan:1.0.0"

# Packaged artifacts
artifacts:
  task_prompt: "prompts/task.prompt.txt"
  qa_prompt: null
  pgc_context: null
  questions_prompt: null
  schema: "schemas/output.schema.json"

# Tests
tests:
  fixtures: []
  golden_traces: []

# Gating rules
gating_rules:
  lifecycle_states: []
  design_status: []
  acceptance_required: true  # Requires acceptance before spawning WPs
  accepted_by:
    - stakeholder
    - technical_lead

# Information Architecture (ADR-054)
information_architecture:
  version: 2

  sections:
    - id: overview
      label: Plan Summary
      binds:
        - path: plan_summary
          render_as: nested-object
          fields:
            - path: overall_intent
              render_as: paragraph
            - path: mvp_definition
              render_as: paragraph
            - path: key_constraints
              render_as: list
            - path: sequencing_rationale
              render_as: paragraph

    - id: work_packages
      label: Work Packages
      binds:
        - path: work_packages
          render_as: card-list
          card:
            title: title
            fields:
              - path: wp_id
                render_as: paragraph
              - path: rationale
                render_as: paragraph
              - path: scope_in
                render_as: list
              - path: scope_out
                render_as: list
              - path: dependencies
                render_as: table
                columns:
                  - field: wp_id
                    label: Depends On
                  - field: dependency_type
                    label: Type
                  - field: notes
                    label: Notes
              - path: definition_of_done
                render_as: list
              - path: governance_pins
                render_as: key-value-pairs
              - path: source_candidate_ids
                render_as: list
              - path: transformation
                render_as: paragraph
              - path: transformation_notes
                render_as: paragraph

    - id: reconciliation
      label: Candidate Reconciliation
      binds:
        - path: candidate_reconciliation
          render_as: table
          columns:
            - field: candidate_id
              label: Candidate
            - field: outcome
              label: Outcome
            - field: resulting_wp_ids
              label: Resulting WPs
            - field: notes
              label: Notes

    - id: risks
      label: Risk Summary
      binds:
        - path: risk_summary
          render_as: table
          columns:
            - field: risk
              label: Risk
            - field: affected_wps
              label: Affected WPs
            - field: overall_impact
              label: Impact
            - field: mitigation_strategy
              label: Mitigation

    - id: concerns
      label: Cross-Cutting Concerns
      binds:
        - path: cross_cutting_concerns
          render_as: list

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview

      - id: work_packages
        label: Work Packages
        sections:
          - work_packages

      - id: reconciliation
        label: Reconciliation
        sections:
          - reconciliation

      - id: risks_concerns
        label: Risks & Concerns
        sections:
          - risks
          - concerns

  pdf:
    linear_order:
      - overview
      - work_packages
      - reconciliation
      - risks
      - concerns
    toc: true

# UI configuration
ui:
  icon: git-branch
  category: planning
  display_order: 35
