# Implementation Plan (Final) Package
# Version 1.0.0 - Initial release

doc_type_id: implementation_plan
display_name: "Implementation Plan"
version: "1.0.0"
description: >
  Final implementation plan produced after technical architecture review.
  Reconciles WP candidates into committed Work Packages with governance
  pinning. Creating this document spawns individual Work Package documents.

# Classification
authority_level: prescriptive  # Prescriptive - defines what will be built
creation_mode: llm_generated
production_mode: generate
scope: project

# Rendering
view_docdef: ImplementationPlanView

# Dependencies
required_inputs:
  - primary_implementation_plan
  - project_discovery
optional_inputs: []
creates_children:
  - work_package
parent_doc_type: null

# Shared artifact references
role_prompt_ref: "prompt:role:project_manager:1.0.0"
template_ref: "prompt:template:document_generator:1.0.0"
schema_ref: "schema:implementation_plan:1.0.0"

# Packaged artifacts
artifacts:
  task_prompt: "prompts/task.prompt.txt"
  qa_prompt: null
  pgc_context: null
  questions_prompt: null
  schema: "schemas/output.schema.json"

# Tests
tests:
  fixtures: []
  golden_traces: []

# Gating rules
gating_rules:
  lifecycle_states: []
  design_status: []
  acceptance_required: true  # Requires acceptance before spawning WPs
  accepted_by:
    - stakeholder
    - technical_lead

# Information Architecture (ADR-054)
information_architecture:
  version: 1

  sections:
    - id: overview
      label: Plan Summary
      binds:
        - plan_summary

    - id: work_packages
      label: Work Packages
      binds:
        - work_packages

    - id: reconciliation
      label: Candidate Reconciliation
      binds:
        - candidate_reconciliation

    - id: risks
      label: Risk Summary
      binds:
        - risk_summary

    - id: concerns
      label: Cross-Cutting Concerns
      binds:
        - cross_cutting_concerns

# Rendering targets (ADR-054)
rendering:
  detail_html:
    layout: tabs
    tabs:
      - id: overview
        label: Overview
        sections:
          - overview

      - id: work_packages
        label: Work Packages
        sections:
          - work_packages

      - id: reconciliation
        label: Reconciliation
        sections:
          - reconciliation

      - id: risks_concerns
        label: Risks & Concerns
        sections:
          - risks
          - concerns

  pdf:
    linear_order:
      - overview
      - work_packages
      - reconciliation
      - risks
      - concerns
    toc: true

# UI configuration
ui:
  icon: git-branch
  category: planning
  display_order: 35
